/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./utils/**/*.{js,ts,jsx,tsx}"],
  plugins: [require("daisyui")],
  darkTheme: "dark",
  darkMode: ["selector", "[data-theme='dark']"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#4ade80",
          "primary-content": "#000000",
          secondary: "#16a34a",
          "secondary-content": "#ffffff",
          accent: "#15803d",
          "accent-content": "#ffffff",
          neutral: "#000000",
          "neutral-content": "#4ade80",
          "base-100": "#ffffff",
          "base-200": "#f4f4f4",
          "base-300": "#e0e0e0",
          "base-content": "#000000",
          info: "#16a34a",
          success: "#4ade80",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "0.25rem",
          ".tooltip": { "--tooltip-tail": "6px" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
      {
        dark: {
          primary: "#4ade80",
          "primary-content": "#000000",
          secondary: "#16a34a",
          "secondary-content": "#4ade80",
          accent: "#15803d",
          "accent-content": "#4ade80",
          neutral: "#4ade80",
          "neutral-content": "#000000",
          "base-100": "#0D0208",
          "base-200": "#13040c",
          "base-300": "#1a0611",
          "base-content": "#4ade80",
          info: "#16a34a",
          success: "#4ade80",
          warning: "#FFCF72",
          error: "#FF8863",
          "--rounded-btn": "0.25rem",
          ".tooltip": { "--tooltip-tail": "6px", "--tooltip-color": "oklch(var(--p))" },
          ".link": { textUnderlineOffset: "2px" },
          ".link:hover": { opacity: "80%" },
        },
      },
    ],
  },
  theme: {
    extend: {
      boxShadow: { center: "0 0 12px -2px rgb(0 0 0 / 0.05)" },
      animation: { "pulse-fast": "pulse 1s cubic-bezier(0.4, 0, 0.6, 1) infinite" },
    },
  },
};
