/**
 * DON'T MODIFY OR DELETE THIS SCRIPT (unless you know what you're doing)
 *
 * This script generates the file containing the contracts Abi definitions.
 * These definitions are used to derive the types needed in the custom scaffold-eth hooks, for example.
 * This script should run as the last deploy script.
 */

import * as fs from "fs";
import prettier from "prettier";
import { DeployFunction } from "hardhat-deploy/types";

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

const DEPLOYMENTS_DIR = "./deployments";
const ARTIFACTS_DIR = "./artifacts";

function getDirectories(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isDirectory())
    .map(dirent => dirent.name);
}

function getContractNames(path: string) {
  return fs
    .readdirSync(path, { withFileTypes: true })
    .filter(dirent => dirent.isFile() && dirent.name.endsWith(".json"))
    .map(dirent => dirent.name.split(".")[0]);
}

function getActualSourcesForContract(sources: Record<string, any>, contractName: string) {
  for (const sourcePath of Object.keys(sources)) {
    const sourceName = sourcePath.split("/").pop()?.split(".sol")[0];
    if (sourceName === contractName) {
      const contractContent = sources[sourcePath].content as string;
      const regex = /contract\s+(\w+)\s+is\s+([^{}]+)\{/;
      const match = contractContent.match(regex);

      if (match) {
        const inheritancePart = match[2];
        // Split the inherited contracts by commas to get the list of inherited contracts
        const inheritedContracts = inheritancePart.split(",").map(contract => `${contract.trim()}.sol`);

        return inheritedContracts;
      }
      return [];
    }
  }
  return [];
}

function getInheritedFunctions(sources: Record<string, any>, contractName: string) {
  const actualSources = getActualSourcesForContract(sources, contractName);
  const inheritedFunctions = {} as Record<string, any>;

  for (const sourceContractName of actualSources) {
    const sourcePath = Object.keys(sources).find(key => key.includes(`/${sourceContractName}`));
    if (sourcePath) {
      const sourceName = sourcePath?.split("/").pop()?.split(".sol")[0];
      const { abi } = JSON.parse(fs.readFileSync(`${ARTIFACTS_DIR}/${sourcePath}/${sourceName}.json`).toString());
      for (const functionAbi of abi) {
        if (functionAbi.type === "function") {
          inheritedFunctions[functionAbi.name] = sourcePath;
        }
      }
    }
  }

  return inheritedFunctions;
}

// `activeNetwork` is the network just deployed (hardhat-deploy saves under `deployments/<network.name>`).
// Only that deployment may contribute a chain block to the merge. Without this filter, getDirectories()
// returns EVERY `deployments/<net>` dir on disk — so a stale `deployments/sepolia` left over from a prior
// real-Sepolia deploy would land in the result and, via the merge below, OVERRIDE the committed (frozen)
// Sepolia block with whatever local state that dir holds — silently drifting a frozen chain that a fresh CI
// checkout (no such dir) can't catch. Restricting to the active network guarantees a single-network deploy
// only ever regenerates its own block; all other chains are preserved from the committed file. (Codex P2, PR #33.)
function getContractDataFromDeployments(activeNetwork?: string) {
  if (!fs.existsSync(DEPLOYMENTS_DIR)) {
    // The in-memory `hardhat` network persists no deployments dir, so `deploy:efs --network hardhat`
    // (the fork rehearsal) reaches here with nothing on disk. That's not an error — the rehearsal is
    // throwaway and writes no deployedContracts.ts. Return empty so the run exits 0. Networks that DO
    // persist deployments (localhost, sepolia, …) still produce the file as before.
    console.log("[generateTsAbis] no deployments dir — skipping deployedContracts.ts (in-memory run).");
    return {} as Record<string, any>;
  }
  const output = {} as Record<string, any>;
  const chainDirs = getDirectories(DEPLOYMENTS_DIR).filter(dir => !activeNetwork || dir === activeNetwork);
  for (const chainName of chainDirs) {
    const chainId = fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/.chainId`).toString();
    const contracts = {} as Record<string, any>;
    for (const contractName of getContractNames(`${DEPLOYMENTS_DIR}/${chainName}`)) {
      const { abi, address, metadata } = JSON.parse(
        fs.readFileSync(`${DEPLOYMENTS_DIR}/${chainName}/${contractName}.json`).toString(),
      );
      // Skip any non-deployment JSON that lands in the deployments dir: a real hardhat-deploy artifact
      // always has both an abi and an address; without this guard such a file would land in
      // deployedContracts.ts as a garbage `{ address: undefined, abi: undefined }` entry and break the
      // frontend typecheck (Codex P2, PR #24). (The Safe-native build/propose artifact `safe-batches.json`
      // that originally motivated this now lives under `deploy-state/`, not `deployments/`, so this is
      // belt-and-suspenders defense for that file.)
      if (!abi || !address) continue;
      const inheritedFunctions = metadata ? getInheritedFunctions(JSON.parse(metadata).sources, contractName) : {};
      contracts[contractName] = { address, abi, inheritedFunctions };
    }
    // Skip a chain that has a `.chainId` marker but NO contract artifacts. The CI Lint job's BARE
    // hardhat node (no CreateX → core skips, 07/08 skip) can leave an empty `deployments/localhost`
    // dir; without this guard the output would be `{ 31337: {} }`, which is non-empty and would
    // CLOBBER the committed deployedContracts.ts to empty. An empty chain contributes nothing.
    if (Object.keys(contracts).length === 0) continue;
    output[chainId] = contracts;
  }
  return output;
}

// Read the chain blocks already committed in deployedContracts.ts so a single-network deploy can preserve
// the chains it didn't deploy (merge-per-chain — see generateTsAbis below). The file is generated TS
// (`const deployedContracts = {…} as const`); we extract the object literal and eval it.
//
// On `eval` safety: the input is THIS repo's own committed, self-generated source file — not user/network
// data. Anyone able to alter it already has write access to these deploy scripts, so eval adds no marginal
// attack surface (it runs at deploy time in the dev/CI toolchain, never at app runtime). Safer parsers don't
// fit: `JSON.parse` rejects the unquoted numeric keys + `as const`, and importing the module is circular and
// would resolve the nextjs `~~/…` path alias from the hardhat package. The literal holds only JSON-compatible
// values (strings/numbers/arrays/objects/bools), so the eval→JSON.stringify round-trip is lossless and
// re-serializes byte-identically. Returns {} when the file is absent or unparseable (first-ever generation,
// or a hand-broken file) — we then fall back to writing only the freshly-deployed chains, never throwing
// mid-deploy.
function getExistingChains(targetPath: string): Record<string, any> {
  // Absent file = first-ever generation: nothing to preserve, write only freshly-deployed chains.
  if (!fs.existsSync(targetPath)) return {};
  // Present-but-unparseable is NOT silently treated as empty: returning {} here would make the merge
  // below delete every chain the current deploy didn't touch — the exact clobber this function exists to
  // prevent. Fail loudly instead so a corrupt/hand-broken file is fixed (e.g. `git checkout`) rather than
  // silently regenerated as a single-chain file.
  const src = fs.readFileSync(targetPath, "utf8");
  const match = src.match(/const\s+deployedContracts\s*=\s*(\{[\s\S]*\})\s*as const/);
  if (!match) {
    throw new Error(
      `[generateTsAbis] could not locate the deployedContracts object in ${targetPath}. Refusing to ` +
        `regenerate: writing now would silently delete chains not in this deploy. Restore the file first.`,
    );
  }
  let parsed: unknown;
  try {
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-eval
    parsed = eval(`(${match[1]})`);
  } catch (e) {
    throw new Error(
      `[generateTsAbis] failed to parse existing ${targetPath} (${(e as Error).message}). Refusing to ` +
        `regenerate and clobber other chains' blocks. Restore the file first.`,
    );
  }
  if (!parsed || typeof parsed !== "object") {
    throw new Error(`[generateTsAbis] parsed ${targetPath} but found no chain object. Refusing to clobber.`);
  }
  return parsed as Record<string, any>;
}

/**
 * Generates the TypeScript contract definition file based on the json output of the contract deployment scripts
 * This script should be run last.
 */
const generateTsAbis: DeployFunction = async function (hre) {
  const TARGET_DIR = "../nextjs/contracts/";
  // Restrict to the network just deployed — only its block may override the committed file (see merge below).
  const deployedChains = getContractDataFromDeployments(hre.network.name);

  // No persisted deployments (e.g. `deploy:efs --network hardhat` fork rehearsal): do NOT write — that
  // would clobber the committed deployedContracts.ts with `{}`. Leave the pinned file untouched.
  if (Object.keys(deployedChains).length === 0) return;

  // Merge-per-chain (multi-chain safe). A deploy targets ONE network, so `deployedChains` only has that
  // network's block. But deployedContracts.ts is multi-chain: it also carries real-network blocks (Sepolia
  // 11155111 today, mainnet later) that a local fork deploy cannot — and must not — reproduce. Overwriting
  // the whole file would silently delete every chain the current deploy didn't touch (this clobbered the
  // frozen Sepolia block once). So preserve existing chains and let freshly-deployed chain(s) override only
  // their own block: the local fork (31337) stays byte-deterministic, frozen real-network blocks pass through
  // verbatim, and `deploy-pin-check` can keep diffing the whole file across all chains. See ADR-0037.
  const allContractsData = { ...getExistingChains(`${TARGET_DIR}deployedContracts.ts`), ...deployedChains };

  const fileContent = Object.entries(allContractsData).reduce((content, [chainId, chainConfig]) => {
    return `${content}${parseInt(chainId).toFixed(0)}:${JSON.stringify(chainConfig, null, 2)},`;
  }, "");

  if (!fs.existsSync(TARGET_DIR)) {
    fs.mkdirSync(TARGET_DIR);
  }
  fs.writeFileSync(
    `${TARGET_DIR}deployedContracts.ts`,
    await prettier.format(
      `${generatedContractComment} import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract"; \n\n
 const deployedContracts = {${fileContent}} as const; \n\n export default deployedContracts satisfies GenericContractsDeclaration`,
      {
        parser: "typescript",
      },
    ),
  );

  console.log(`📝 Updated TypeScript contract definition file on ${TARGET_DIR}deployedContracts.ts`);
};

export default generateTsAbis;
